#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase


filepath="0/"
rm ${filepath}"cf"
rm ${filepath}"cp"
rm ${filepath}"nuTurb"
rm ${filepath}"vorticity"
rm ${filepath}"wallShearStress"
rm ${filepath}"yPlus"
#------------------------------------------------------------------------------
