#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


mesh="2D_Mesh_250x100.unv"


from="../Meshes/"${mesh}
cp $from .

modifyMesh="system/modifyMeshEntries.py"
python fieldsValues.py
ideasUnvToFoam $mesh
python $modifyMesh

. $WM_PROJECT_DIR/bin/tools/RunFunctions
application="$(getApplication)"

$application

foamToVTK

#------------------------------------------------------------------------------
