#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"
mesh="Mesh_1.unv"
modifyMesh="system/modifyMeshEntries.py"

ideasUnvToFoam $mesh
python $modifyMesh
python fieldsValues.py

$application
#runApplication $application

foamToVTK


#simpleFoam -postProcess -func vorticity -latestTime
#simpleFoam -postProcess -func wallShearStress -latestTime
#simpleFoam -postProcess -func yPlus -latestTime



# simpleFoam -postProcess -func "grad(U)"

# add(U,U)
# grad(U)
# div(U)
# mag(U)

#------------------------------------------------------------------------------
