#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions

mesh="Mesh_1.unv"
modifyMesh="system/modifyMeshEntries.py"

python fieldsValues.py
ideasUnvToFoam $mesh
python $modifyMesh

. $WM_PROJECT_DIR/bin/tools/RunFunctions
application="$(getApplication)"

$application
#runApplication $application

foamToVTK




#------------------------------------------------------------------------------
