#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

Mesh="Mesh_1.unv"

ideasUnvToFoam $Mesh
python mod.py

$application
#runApplication $application

# $application postProcess -func vorticity
# $application postProcess -func wallShearStress
# $application postProcess -func yPlus


#------------------------------------------------------------------------------
