#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


mesh="3D_150x50x20.unv"


from="../Meshes/"${mesh}
cp $from .

modifyMesh="system/modifymesh.py"
ideasUnvToFoam $mesh
python $modifyMesh

. $WM_PROJECT_DIR/bin/tools/RunFunctions
application="$(getApplication)"

$application


#------------------------------------------------------------------------------